---
# tasks file for roles/postgres

- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: enable postgresql at boot
  service:
    name: postgresql
    enabled: yes

#- name: check for existing postgres data directory
#  stat: path=/var/lib/pgsql
#  register: postgres_data

- name: initilize postgres
  command: postgresql-setup initdb creates=/var/lib/pgsql
#  when: not postgres_data.stat.exists

- name: start postgres
  service:
    name: postgresql.service
    state: started

